/// @file   core.h
/// @brief  aggregate include file for the 'core' project
#pragma once

// ----------------------------------------------------------------------------
// DataStructures
// ----------------------------------------------------------------------------
#include "core\Array.h"
#include "core\ConstSizeArray.h"
#include "core\Point.h"
#include "core\Stack.h"
#include "core\LocalStack.h"
#include "core\List.h"
#include "core\LocalList.h"
#include "core\Dequeue.h"
#include "core\CollectionUtils.h"
#include "core\RawArrayUtil.h"
#include "core\ListUtils.h"
#include "core\ArrayUtils.h"
#include "core\CollectionComparators.h"
#include "core\Grid.h"
#include "core\BestResultsList.h"
// ----------------------------------------------------------------------------
// -->Graphs
// ----------------------------------------------------------------------------
#include "core\Graph.h"
#include "core\GraphUtils.h"
#include "core\GraphBuilder.h"
#include "core\GraphBuilderNode.h"
#include "core\GraphBuilderSockets.h"
#include "core\GraphBuilderTransaction.h"
// ----------------------------------------------------------------------------
// Delegates
// ----------------------------------------------------------------------------
#include "core\Delegate.h"

// ----------------------------------------------------------------------------
// Filesystem
// ----------------------------------------------------------------------------
#include "core\File.h"
#include "core\Filesystem.h"
#include "core\FilesystemSection.h"
#include "core\StreamBuffer.h"
#include "core\FilePath.h"
#include "core\FilesystemUtils.h"

// ----------------------------------------------------------------------------
// Geometry
// ----------------------------------------------------------------------------
#include "core\PolygonMesh2D.h"
#include "core\MeshAdjacencyMap.h"

// ----------------------------------------------------------------------------
// Logging
// ----------------------------------------------------------------------------
#include "core\Assert.h"
#include "core\IProgressObserver.h"
#include "core\Log.h"

// ----------------------------------------------------------------------------
// Math
// ----------------------------------------------------------------------------
#include "core\Math.h"

// ----------------------------------------------------------------------------
// MemoryManagement
// -->Pools
// ----------------------------------------------------------------------------
#include "core\ContinuousMemoryPool.h"
#include "core\TSContinuousMemoryPool.h"
#include "core\FragmentedMemoryPool.h"
#include "core\TSFragmentedMemoryPool.h"
#include "core\RuntimeData.h"
#include "core\RoundBuffer.h"
#include "core\ClientServerRoundBuffer.h"
// ----------------------------------------------------------------------------
// -->Core
// ----------------------------------------------------------------------------
#include "core\MemoryRouter.h"
#include "core\MemoryUtils.h"
#include "core\MemoryAllocator.h"
// ----------------------------------------------------------------------------
// -->Callstacks
// ----------------------------------------------------------------------------
#include "core\CallstackTracer.h"
#include "core\CallstackTree.h"
// ----------------------------------------------------------------------------
// -->Allocators
// ----------------------------------------------------------------------------
#include "core\DefaultAllocator.h"

// ----------------------------------------------------------------------------
// Misc
// ----------------------------------------------------------------------------
#include "core\Color.h"
#include "core\GenericFactory.h"
#include "core\Observer.h"
#include "core\Subject.h"
#include "core\IntervalOperation.h"
#include "core\UniqueObject.h"
#include "core\UniqueIdGenerator.h"
#include "core\StringUtils.h"
#include "core\StringParser.h"
#include "core\Singleton.h"
#include "core\IDString.h"
#include "core\SharedValue.h"

// ----------------------------------------------------------------------------
// Multithreading
// -->Core
// ----------------------------------------------------------------------------
#include "core\ThreadSystem.h"
#include "core\Thread.h"
#include "core\Runnable.h"
// ----------------------------------------------------------------------------
// -->Synchronization
// ----------------------------------------------------------------------------
#include "core\Mutex.h"
#include "core\Semaphore.h"
// ----------------------------------------------------------------------------
// -->TasksScheduler
// ----------------------------------------------------------------------------
#include "core\MultithreadedTasksScheduler.h"
#include "core\MultithreadedTask.h"
// ----------------------------------------------------------------------------
// -->LocklessCommandsQueue
// ----------------------------------------------------------------------------
#include "core\LocklessCommand.h"
#include "core\LocklessCommandsQueue.h"
#include "core\SteppedLocklessCommandsQueue.h"
// ----------------------------------------------------------------------------
// -->Utils
// ----------------------------------------------------------------------------
#include "core\ThreadSafe.h"
#include "core\ThreadSafe.h"
// ----------------------------------------------------------------------------
// -->EventsDispatcher
// ----------------------------------------------------------------------------
#include "core\EventsDispatcher.h"
#include "core\Event.h"

// ----------------------------------------------------------------------------
// RTTI
// -->Core
// ----------------------------------------------------------------------------
#include "core/ReflectionObject.h"
#include "core/ReflectionType.h"
#include "core/ReflectionTypeComponent.h"
#include "core/ReflectionTypeID.h"
#include "core/ReflectionTypesRegistry.h"
#include "core/ReflectionObjectChangeListener.h"
#include "core/ReflectionDependenciesCallback.h"
#include "core/types.h"
// ----------------------------------------------------------------------------
// -->Enum
// ----------------------------------------------------------------------------
#include "core/ReflectionEnum.h"
// ----------------------------------------------------------------------------
// -->Properties
// ----------------------------------------------------------------------------
#include "core/ReflectionPropertiesView.h"
#include "core/ReflectionProperty.h"
#include "core/ReflectionPropertyEditor.h"
// ----------------------------------------------------------------------------
// -->Patches
// ----------------------------------------------------------------------------
#include "core/PatchesDB.h"
#include "core/PatchRecord.h"
#include "core/PatchesDBMacros.h"
#include "core/PatchesDBSerializer.h"
// ----------------------------------------------------------------------------
// -->RefPtr
// ----------------------------------------------------------------------------
#include "core/RefPtr.h"
// ----------------------------------------------------------------------------
// -->Serialization
// ----------------------------------------------------------------------------
#include "core/ReflectionSaver.h"
#include "core/ReflectionLoader.h"
#include "core/ReflectionObjectsTracker.h"
#include "core/ReflectionSerializationUtil.h"
#include "core/SerializedReflectionObject.h"

// ----------------------------------------------------------------------------
// Resources
// ----------------------------------------------------------------------------
#include "core\Resource.h"
#include "core\ResourcesManager.h"
#include "core\ResourceStorage.h"
#include "core\ResourceHandle.h"
// ----------------------------------------------------------------------------
// -->DependenciesMapper
// ----------------------------------------------------------------------------
#include "core\ResourceDependenciesMapper.h"
// ----------------------------------------------------------------------------
// -->ResourceUtils
// ----------------------------------------------------------------------------
#include "core\ResourceUtils.h"
// ----------------------------------------------------------------------------
// -->Serialization
// ----------------------------------------------------------------------------
#include "core\ResourcesSerializationUtil.h"

// ----------------------------------------------------------------------------
// SpatialStorage
// ----------------------------------------------------------------------------
#include "core\BSPNodeTree.h"
#include "core\LinearStorage.h"

// ----------------------------------------------------------------------------
// Streams
// ----------------------------------------------------------------------------
#include "core\dostream.h"
#include "core\InStream.h"
#include "core\OutStream.h"
// ----------------------------------------------------------------------------
// -->Implementations
// ----------------------------------------------------------------------------
#include "core/InArrayStream.h"
#include "core/OutArrayStream.h"
#include "core/InFileStream.h"
#include "core/OutFileStream.h"
#include "core/InRawArrayStream.h"
#include "core/OutRawArrayStream.h"

// ----------------------------------------------------------------------------
// Timer
// ----------------------------------------------------------------------------
#include "core\Timer.h"
#include "core\Profiler.h"

// ----------------------------------------------------------------------------
// TimeController
// ----------------------------------------------------------------------------
#include "core\TimeController.h"
#include "core\TimeControllerTrack.h"
#include "core\TimeDependent.h"
#include "core\TimeEvent.h"
